const fs=require('fs');
const path=require('path');
const file=path.join(__dirname,'src','App.jsx');
let s=fs.readFileSync(file,'utf8');
const MARK='PDF A4 portrait isolated fix v5';
if(s.includes(MARK)){console.log('PDF v5 já aplicado.');process.exit(0);}
const start=s.indexOf('const handleExportPDF = async');
const end=s.indexOf('  return (',start);
if(start<0||end<0) throw new Error('Função handleExportPDF não encontrada.');
let pdf=s.slice(start,end);
pdf=pdf.replace("container.style.padding = '24px';","container.style.padding = '0';");
pdf=pdf.replace("container.style.width = '1120px';",`/* ${MARK}: A4 portrait em viewport fixo */\n      container.style.width = '794px';\n      container.style.maxWidth = '794px';\n      container.style.margin = '0';\n      container.style.position = 'absolute';\n      container.style.left = '-10000px';\n      container.style.top = '0';`);
pdf=pdf.replace("container.style.width = '1062px';",`/* ${MARK}: A4 portrait em viewport fixo */\n      container.style.width = '794px';\n      container.style.maxWidth = '794px';\n      container.style.margin = '0';\n      container.style.position = 'absolute';\n      container.style.left = '-10000px';\n      container.style.top = '0';`);
pdf=pdf.replace(/@page \{ size: A4 landscape; margin: 8mm; \}/g,'@page { size: A4 portrait; margin: 0; }');
pdf=pdf.replace(/\.pdf-report \{ width: 281mm; max-width: 281mm; margin: 0; padding: 0; overflow: visible; \}/g,'.pdf-report { width: 794px; max-width: 794px; margin: 0; padding: 24px; overflow: visible; box-sizing: border-box; }');
pdf=pdf.replace(/\.pdf-section, \.pdf-kpi, \.pdf-monitoria \{ page-break-inside: avoid; break-inside: avoid; \}/g,'.pdf-section, .pdf-kpi { page-break-inside: avoid; break-inside: avoid; }\n          .pdf-monitoria { page-break-inside: auto; break-inside: auto; }');
pdf=pdf.replace(/<div class="pdf-report" style="width: 281mm; max-width: 281mm; margin: 0; padding: 0;">/g,'<div class="pdf-report" style="width: 794px; max-width: 794px; margin: 0; padding: 24px; box-sizing: border-box;">');
pdf=pdf.replace(/<div style="display: flex; flex-direction: column; gap: 12px;">/g,'<div class="pdf-monitoria-list">');
pdf=pdf.replace(/<div style="display: flex; gap: 15px; font-size: 10px; margin-bottom: 6px;">/g,'<div class="pdf-meta-row" style="display: flex; flex-wrap: wrap; gap: 10px 15px; font-size: 10px; margin-bottom: 6px;">');
pdf=pdf.replace(/windowWidth: 1120/g,'windowWidth: 794').replace(/windowWidth: 1062/g,'windowWidth: 794').replace(/width: 1062/g,'width: 794');
if(!pdf.includes('windowWidth: 794,\n          width: 794')) pdf=pdf.replace(/windowWidth: 794,/, 'windowWidth: 794,\n          width: 794,');
pdf=pdf.replace(/orientation: 'landscape'/g,"orientation: 'portrait'");
pdf=pdf.replace(/margin: \[8, 8, 10, 8\]/g,'margin: [10, 10, 10, 10]');
pdf=pdf.replace(/avoid: \['\.pdf-section', '\.pdf-kpi', '\.pdf-monitoria'\]/g,"avoid: ['.pdf-section', '.pdf-kpi']");
pdf=pdf.replace(/page-break-inside: avoid;/g,'page-break-inside: auto;');
pdf=pdf.replace(/\.pdf-section, \.pdf-kpi \{ page-break-inside: auto; break-inside: avoid; \}/g,'.pdf-section, .pdf-kpi { page-break-inside: avoid; break-inside: avoid; }');
if(!pdf.includes('class="pdf-report"')){
  pdf=pdf.replace('<!-- Cabeçalho Institucional -->','<div class="pdf-report" style="width: 794px; max-width: 794px; margin: 0; padding: 24px; box-sizing: border-box;">\n        <!-- Cabeçalho Institucional -->');
  const last=pdf.lastIndexOf('</div>');
  if(last<0) throw new Error('Não foi possível fechar o wrapper PDF.');
  pdf=pdf.slice(0,last)+'</div>\n'+pdf.slice(last);
}
pdf=pdf.replace(/const clonedContainer = clonedDoc\.querySelector\([^\n]+\);/,"const clonedReport = clonedDoc.querySelector('.pdf-report');");
pdf=pdf.replace(/if \(clonedContainer\) \{([\s\S]*?)\n\s*\}/,`if (clonedReport) {\n              clonedReport.style.width = '794px';\n              clonedReport.style.maxWidth = '794px';\n              clonedReport.style.margin = '0';\n            }`);
if(!pdf.includes(MARK)) throw new Error('Marcador v5 não inserido.');
if(!pdf.includes("orientation: 'portrait'")) throw new Error('Portrait não aplicado.');
if(!pdf.includes("container.style.width = '794px';")) throw new Error('Largura 794px não aplicada.');
s=s.slice(0,start)+pdf+s.slice(end);
fs.writeFileSync(file,s,'utf8');
console.log('PDF A4 retrato v5 aplicado.');
